Encoder for Wasm tail calls
paritytech/parity-wasm pull request #313
Opened 2021-08-23 17:21 UTC by arjunguha

This is a trivial commit that adds support for Wasm tail calls, which are available in Node/V8 with the `--experimental-wasm-return_call` flag.

2021-09-01 14:23 UTC, athei commented
Thanks for you PR. Can you add the decoder, too? We also have the convention in this repository that everything that is not part of the MVP must be guarded behind a cargo feature.

2021-09-02 14:18 UTC, arjunguha commented
Sure, will do. It will take a few days for me to get to it.

2022-01-17 18:01 UTC, arjunguha commented
It took me forever to get to this, and @CosineP took care of it. This PR has:

1. Tail calls behind a feature flag
2. Tail call encoder
3. Tail call decoder

2022-01-18 08:06 UTC, athei requested changes
Thanks this looks much better. But we obviously can't merge without tests.

* Please satisfy the CI
* Activate the tail call proposal directory in the test suite (you also need to activate the feature)
* Add a test for the encoder

2022-06-03 13:22 UTC, closed without merging